name: CI

on:
  repository_dispatch:
  workflow_dispatch:

  # TODO: delete before merge!!!
  push:
    branches:
      - "ci"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/ci.yml"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install depdendencies
      run: python3 -m pip install aiohttp requests

    - name: Generate Dataset
      run: python3 scripts/gen_dataset.py

    - name: Configure
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build -j

    - name: Run tests
      run: |
        echo "# Tests" >> summary.md
        echo "```" >> summary.md
        ./build/notification_tests >> summary.md
        echo "```" >> summary.md

    - name: Run benchmarks
      run: |
        echo "# Benchmarks" >> summary.md
        echo "```" >> summary.md
        ./build/notification_bench >> summary.md
        echo "```" >> summary.md

    - name: Run service in background
      run: ./build/notification_service &

    - name: Preload dataset
      run: python3 scripts/preload.py --url http://localhost:8080

    - name: Run load test
      run: |
        echo "# Tests" >> summary.md
        echo "```" >> summary.md
        python3 scripts/load_test.py --url http://localhost:8080 --duration 60s --concurrency 50 >> summary.md
        echo "```" >> summary.md

    - name: Publish summary
      run: cat summary.md > "$GITHUB_STEP_SUMMARY"
